---
title: "SQL&R_test_Rodrigo_Rioseco"
author: "Rodrigo_Rioseco"
date: "2023-03-31"
output: html_document
---

```{sql connection=}
#1
SELECT "Address" FROM Customers;
#2
SELECT DISTINCT City FROM Customers;
#3
SELECT * FROM Customers
WHERE City = 'Berlin' OR City = 'Madrid';
#4
SELECT *
FROM Orders
LEFT JOIN Customers 
ON Orders.CustomerID=Customers.CustomerID;
#5
SELECT COUNT(CustomerID),City
FROM Customers
GROUP BY City
ORDER BY COUNT(CustomerID) DESC;
```


```{r}
#1 Importa los datos del archivo en CSV “Market_size” del repo del curso, estos se usarán para las 4 siguientes preguntas. En este chunk deberás poner todas las librerías utilizadas.
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(ggplot2)
datos <- read.csv("C:/Users/Rodrigo/Desktop/TEC/Concentracion/Market_size.csv", skip = 5, fileEncoding = "latin1")
View(datos)
str(datos)
datos$X2017 <- as.numeric(datos$X2017)
datos$X2018 <- as.numeric(datos$X2018)
datos$X2019 <- as.numeric(datos$X2019)
datos$X2020 <- as.numeric(datos$X2020)
datos$X2021 <- as.numeric(datos$X2021)
datos$X2022 <- as.numeric(datos$X2022)
datos$X2023 <- as.numeric(datos$X2023)
datos <- na.omit(datos)
```

```{r}
#2 Genera una tabla que muestre los precios del 2023 para México de todas las categorías de bebidas.
p2023 = filter(datos, Geography == "Mexico") %>% 
          select(Geography, Category, X2023)
View(p2023)
```

```{r}
#3 Genera una tabla que muestre por país y por categoría el precio por litro promedio de bebidas de cada año. Hint. Market Size
pl <- datos %>%
  select(Geography, Category, X2017, X2018, X2019, X2020, X2021, X2022, X2023) %>%
  group_by(Geography, Category) %>%
  summarise(`p_2017` = mean(X2017),
            `p_2018` = mean(X2018),
            `p_2019` = mean(X2019),
            `p_2020` = mean(X2020),
            `p_2021` = mean(X2021),
            `p_2022` = mean(X2022),
            `p_2023` = mean(X2023))
View(pl)
```

```{r}
#4 A partir de la tabla anterior, genera un gráfico que muestre solo los países que inician con la letra “B” y sus precios por año contable. Recuerda usa tu creatividad, puedes usar geometrías vistas en clase u otras nuevas!
pl_b = pl %>% filter(str_starts(Geography, "B"))
nueva_pl = pl_b %>% 
  pivot_longer(cols = c("p_2017", "p_2018", "p_2019", "p_2020", "p_2021", "p_2022", "p_2023"),
               names_to = "Año",
               values_to = "precio")
print(ggplot(nueva_pl, aes(x = Año, y = precio, fill = Geography)) +
  geom_col() +
  labs(title = "Precios por año con paises con 'B'",
       x = "Año",
       y = "Precio") +
  scale_fill_manual(values = c("red", "blue", "green", "orange")))
```


```{r}
#5 Genera un mapa de calor, que muestre al menos 1 de los dos valores numéricos de los datos de Market (Litros o Precios) en función de cualquier variable. Se creativo con los colores!
print(ggplot(filter(datos, Geography %in% c("Mexico", "USA", "Canada")), aes(Category, Geography, fill = X2023)) + 
  geom_tile() + 
  scale_fill_gradient(low = "blue", high = "red") +
  labs(title = "Precios de America del norte en el 2023",
       x = "Categoría",
       y = "Paises",
       fill = "Precios") + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.2)))
```
