
# 1. Genera un Query que seleccione la columna Address de la tabla Customers.

SELECT Address FROM Customers;

# 2. Genera un Query que seleccione todos los diferentes valores de la columna City de la tabla Customers.

SELECT DISTINCT City FROM Customers;


# 3. Genera un Query que seleccione todos los registros en donde la columna City tenga los valores de Berlin ó Madrid.

SELECT * FROM Customers WHERE City = 'Berlin' OR City = 'Madrid';

# 4. Completa el siguiente Query, elije el JOIN correcto que seleccione todos los registros de la tabla Customers mas todas las coincidencias en la tabla Orders.

SELECT *
FROM Orders
LEFT JOIN Customers ON Orders.CustomerID=Customers.CustomerID;

# 5. Completa el siguiente Query, lista el numero de clientes en cada ciudad, y ordena la lista de acuerdo con el mayor numero de clientes de forma descendente.

SELECT COUNT(CustomerID), City
FROM Customers
GROUP BY City
ORDER BY COUNT(CustomerID) DESC;

#### Data VIZ

library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(ggplot2)

df = read_csv("C:/Users/paola/Desktop/Data_Transformation_Viz/data/Market_size.csv",skip = 5)

# Genera una tabla que muestre los precios del 2023 para México de todas las categorías de bebidas.

Mexico_23 <- df %>%
  filter(Geography  == "Mexico") %>%
  select("Geography", "2023", "Unit", "Category")
  



# Genera una tabla que muestre por país y por categoría el precio por litro promedio de bebidas de cada año. 

precio_promedio <- df %>%
  select(Geography, Category, starts_with("20")) %>%
  pivot_longer(cols = starts_with("20"), names_to = "Year", values_to = "Precio_por_litro") %>%
  mutate(Year = as.numeric(Year)) %>%
  group_by(Geography, Category, Year) %>%
  summarise(precio_promedio_por_litro = mean(as.numeric(Precio_por_litro), na.rm = TRUE))

#A partir de la tabla anterior, genera un gráfico que muestre solo los países que inician con la letra “B” y sus precios por año contable 

paises_b <- precio_promedio %>%
  filter(str_sub(Geography, 1, 1) == "B")%>%
  mutate(Year = factor(Year, levels = c("2017", "2018", "2019", "2020", "2021", "2022", "2023")))
  
ggplot(paises_b, aes(x = Year, y = precio_promedio_por_litro, color = Geography)) +
  geom_point(size = 3) +
  scale_color_brewer(palette = "Dark2") +
  labs(title = "Precios por año contable para países que comienzan con 'B'",
       x = "Año", y = "Precio promedio por litro")

# Genera un mapa de calor, que muestre al menos 1 de los dos valores numéricos de los datos de Market (Litros o Precios) en función de cualquier variable. Se creativo con los colores!

df2 <- df %>%
  select(Geography, Unit, starts_with("20")) %>%
  filter(Unit == "million litres" & Geography %in% c("China", "Mexico", "Canada"))

# Convertir los datos a formato largo
df_long <- df2 %>%
  pivot_longer(cols = starts_with("20"), names_to = "Year", values_to = "Litros") %>%
  mutate(Year = as.numeric(Year)) %>%
  drop_na()

# Generar mapa de calor
ggplot(df_long, aes(x = Geography, y = Year, fill = Litros)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "darkblue") +
  labs(title = "Litros por país y año",
       x = "País", y = "Año", fill = "Litros (millones)") 

  
  